// actionTypes.js

//dashboard
export const SET_IS_LOADING = 'SET_IS_LOADING'


export const FETCH_PLAYER_DATA_REQUEST = 'FETCH_PLAYER_DATA_REQUEST';

export const SET_PLAYER_DATA = 'SET_PLAYER_DATA'

export const FETCH_PLAYER_DATA_SUCCESS = 'FETCH_PLAYER_DATA_SUCCESS';
export const FETCH_PLAYER_DATA_FAILURE = 'FETCH_PLAYER_DATA_FAILURE';


export const UPDATE_PLAYER_DATA_REQUEST = 'UPDATE_PLAYER_DATA_REQUEST';
export const UPDATE_PLAYER_DATA_SUCCESS = 'UPDATE_PLAYER_DATA_SUCCESS';
export const UPDATE_PLAYER_DATA_FAILURE = 'UPDATE_PLAYER_DATA_FAILURE';


export const DELETE_PLAYER_DATA_REQUEST = 'DELETE_PLAYER_DATA_REQUEST';
export const DELETE_PLAYER_DATA_SUCCESS = 'DELETE_PLAYER_DATA_SUCCESS';
export const DELETE_PLAYER_DATA_FAILURE = 'DELETE_PLAYER_DATA_FAILURE';

// Add more action types as needed
